### ISSUE TITLE
Issue with column names in dplyr workflows

### ISSUE THREAD

**Issue by gregleleu** [HenrikBengtsson/globals#35]
Hi,
I'm having issues with global in dplyr workflows.
For example, running:
```
out %<-% {my_df %>% group_by(id_var) %>% left_join(other_df) %>% summarise(n = sum(a))}
```
globals (used from the future package) identifies "id_var" as a global object to be exported, when it is only a column name from "my_df".

I'm going around it by explicitly listing globals (e.g. "my_df", and "other_df"), but shouldn't globals be able to pick up on that?

Thanks!

**Comment by HenrikBengtsson** [comment]
It's actually impossible(*) to know from static code inspection whether a symbol in R is a global variable or not.  That is only possible to know at run time. This is regardless of parallel framework - it is the nature of the R language and the non-standard evaluation it supports.  (*) By impossible I mean that you need to be able perfectly emulate how all code is executed, which basically mean you need to run it.  Here is an example illustrating it:

```r
fcn1 <- function(x) 2 * x
fcn2 <- function(x) as.character(substitute(x))
```

There is no way to know from static code inspection that `fcn1(foo)` needs `foo` whereas `fcn2(foo)` it only cares about the _name_ (`"foo"`).


So, with this limitation we can only make clever guesses.  Also, depending on your objectives, you can take a conservative approach where you're saying "I'm ok with missing a few global variables, but I absolute do not want to find false globals", or you can take a liberal approach where you're saying "I prefer to find all globals for the price of finding a few false ones".

In parallel processing where you need to make sure your external R worker has access to all objects it needs, you have to take the liberal approach.  That is the default setup of the 'globals' package and what the 'future' framework needs.

So, in your code snippet, you will get that:

```r
> expr <- quote({ my_df %>% group_by(id_var) %>% left_join(other_df) %>% summarise(n = sum(a)) })
> expr
{
    my_df %>% group_by(id_var) %>% left_join(other_df) %>% summarise(n = sum(a))
}
> vars <- globals::findGlobals(expr)
> vars
 [1] "{"         "%>%"       "my_df"     "group_by"  "id_var"    "left_join"
 [7] "other_df"  "summarise" "sum"       "a"        
```

and there you see that it lists `id_var` as a global variable _name_.

Now, does this exist or not?  That completely depend on what objects exist in your environment, e.g.

```r
> library(dplyr)
> my_df <- data.frame(a = 1:10, id_var = rep(c("a", "b"), each = 5))
> other_df <- data.frame(a = 1:10, b = 10:1)
> globals <- globals::cleanup(globals::globalsOf(expr, mustExist = FALSE))
> str(globals)
List of 7
 $ %>%      :function (lhs, rhs)  
 $ my_df    :'data.frame':	10 obs. of  2 variables:
  ..$ a     : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ id_var: Factor w/ 2 levels "a","b": 1 1 1 1 1 2 2 2 2 2
 $ group_by :function (.data, ..., add = FALSE)  
 $ left_join:function (x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ...)  
 $ other_df :'data.frame':	10 obs. of  2 variables:
  ..$ a: int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ b: int [1:10] 10 9 8 7 6 5 4 3 2 1
 $ summarise:function (.data, ...)  
 $ a        : num 1
[...]
```

As you see, only some of the objects identify by `findGlobals()` are actually picked up by `globalsOf()`.  In other words, `id_var` is _not_ a global variable exported to the external R worker.

Now, which might be what you observed but your claim didn't come with much background info, if you happen to have a global variable `id_var` sitting in your environment, then, yes, it'll be picked up, e.g.

```r
> id_var <- "dummy"
> globals <- globals::cleanup(globals::globalsOf(expr, mustExist = FALSE))
> str(globals)
List of 8
 $ %>%      :function (lhs, rhs)  
 $ my_df    :'data.frame':	10 obs. of  2 variables:
  ..$ a     : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ id_var: Factor w/ 2 levels "a","b": 1 1 1 1 1 2 2 2 2 2
 $ group_by :function (.data, ..., add = FALSE)  
 $ id_var   : chr "dummy"
 $ left_join:function (x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ...)  
 $ other_df :'data.frame':	10 obs. of  2 variables:
  ..$ a: int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ b: int [1:10] 10 9 8 7 6 5 4 3 2 1
 $ summarise:function (.data, ...)  
 $ a        : num 1
[...]
```

So, in this case, using a liberal, optimistic approach a future that look like:
```r
out %<-% { my_df %>% group_by(id_var) %>% left_join(other_df) %>% summarise(n = sum(a)) }
```
will send of `id_var` (= `"dummy"`) to the worker/environment where the future expression is evaluated.  However, this will not be used in the evaluation; just as it won't be used if you evaluate it locally:
```r
out <- { my_df %>% group_by(id_var) %>% left_join(other_df) %>% summarise(n = sum(a)) }
```

Hope this clarifies.

**Comment by gregleleu** [comment]
Hi, thanks for the detailed answer.
I understand the complexity; so I went back to my code, and as per your code it turns out: 

- it all works fine when run "directly" (case A below), 
- also within a function called "directly" (case B) 
- but not when the function is called through future_lapply (case C) 

With an example closer to what I'm actually doing:
**Case A** -- works fine
```
my_df_sub %<-% { my_df %>% filter(id_var %in% id_var_vec) }
```
=> no issue

**Case B**  -- works fine
```
my_func <- function(id_var_vec) { 
  my_df_sub %<-% { my_df %>% filter(id_var %in% id_var_vec) }
  ## Expensive calculations not shown
  return(out)
}
res <- my_func(c("a"))
```
`my_df` is in .GlobalEnv
=> no issue

**Case C** -- doesn't work
```
my_func <- function(id_var_vec) { 
  my_df_sub %<-% { my_df %>% filter(id_var %in% id_var_vec) }
  ## Expensive calculations not shown
  return(out)
}
res <- c("a") %>% future_lapply(my_func)
# Or even just res %<-% my_func(c("a"))
```
=> throws a "simpleError" saying it can't find global objet `id_var`.
I get that this is creating a second level of futures, and I imagine this is where it breaks, I just can't understand why. I fixed it declaring the right %globals% for the%<-% assignment inside the function.


_A tiny bit more context:_
The computations are quite expensive in the function (geospatial analysis). 
Sometimes I run just one "id_var" and I need the "single-id" version (case B) to be parallelized (but it only uses 2-4 of my 8 cores) and sometimes I need to run multiple "id_var"s, hence the 2nd layer of futures.
By the way, in the latter case I understand the deeper layer is run sequentially. My id_var subsets are not well balanced so I tried tweaking the plan to `plan(list(tweak(multiprocess, workers = 4), tweak(multiprocess, workers = 2)))` but I couldn't make it work: I always got a "bad error" message...

Thanks again !!

**Comment by HenrikBengtsson** [comment]
This has been fixed in the [develop branch of future](https://github.com/HenrikBengtsson/future/commit/f33d03e4d4f27adb9a7ece734163352cd854cbfd) - it'll be part of the next release, i.e. future 1.8.0.  In the meanwhile, you can workaround the problem by doing:
```r
library("future")
options(future.globals.onMissing = "ignore")
```

I'm closing this one, but if the above doesn't fix it, please report back. Thanks again for the report.
