### ISSUE TITLE
findGlobals() introduces a warning when the expression is a list with no globals (on R <3.5)

### ISSUE THREAD

**Issue by DavisVaughan** [HenrikBengtsson/globals#41]
I think this is related to some of the newer changes we worked on awhile back regarding searching `X` for globals (in case `X` is a list of functions or something).

``` r
library(globals)
findGlobals(list(1, 1, 1))
#> Warning in is.na(x): is.na() applied to non-(list or vector) of type 'NULL'
#> NULL


library(future.apply)
future_lapply(list(1, 2), identity)
#> Warning in is.na(x): is.na() applied to non-(list or vector) of type 'NULL'
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
```

Specifically, the warning shows up [here](https://github.com/HenrikBengtsson/globals/blob/d372fbec768643674d9ae11dc964f3ab29d8ecd0/R/findGlobals.R#L200) where you run `sort(unique(globals))` where `globals = NULL`

**Comment by DavisVaughan** [comment]
Cheap solutions:

1) Why do you sort there?
2) Check if `NULL` and just skip that step if so (feels like a hack to me)

**Comment by HenrikBengtsson** [comment]
Ah... that `sort()` warning shows up only under R (< 3.5.0).  I'll fix.  Thxs.

PS. Yes, the `sort()` is probably a remnant from the past and unnecessary.  I'll see if I can remove it.

**Comment by DavisVaughan** [comment]
Great, I appreciate it!

**Comment by HenrikBengtsson** [comment]
Forgot to say, this has been fixed in the develop branch.
