### ISSUE TITLE
Do you really need `installed.packages()` in `cleanup()`?

### ISSUE THREAD

**Issue by DavisVaughan** [HenrikBengtsson/globals#42]
In `find_base_pkgs()` there is a call to `installed.packages()`. The first time this is called is actually pretty slow. I've been timing it at around 200ms. Repeated calls are cached so they are fast.

Since this is used just to get base R packages, and those are fairly stable, could we replace this with a hardcoded vector or come up with another way to get at this?

`installed.packages()` can actually be _extremely_ slow on some network drives, which is another reason to not use it. Here is an example I shared with Kevin Ushey of RStudio about this, using my work network drive.

```r
# Local C drive pkgs
system.time(list.files(.libPaths()))
#>    user  system elapsed 
#>       0       0       0
system.time(installed.packages())
#>    user  system elapsed 
#>    0.18    0.16    0.34

.libPaths("R:/Vaughan/R/r-libs")

system.time(list.files(.libPaths()))
#>    user  system elapsed 
#>    0.00    0.00    0.07
system.time(installed.packages())
#>    user  system elapsed 
#>    0.19    0.75   71.42
```

**Comment by DavisVaughan** [comment]
In the broader scheme of things, this helps with showing off the `future` framework, even for "simple" examples where something is already lightning fast with base R, and you just want to compare it to how it would perform in parallel. As a user, I'd be looking to see how much overhead there was in moving to parallel, and this would get rid of sum of that.

**Comment by HenrikBengtsson** [comment]
I've now removed the usage of `installed.packages()` and instead resort to, memoized, `packageDescription(pkg, fields = "Priority")` on a package-by-package basis. Several packages are memoized already when globals is loaded, further hiding some of the overhead. Since only a small number of packages are ever considered in `globals:::is_base_pkg()`, the overhead should be small.

Please have a look.

PS. Don't really wanna hardcode the set of "base" packages - doesn't pass the "maintainer gets hit by the bus" sanity check.

**Comment by DavisVaughan** [comment]
This looks good. Essentially you memoize a set of currently known base packages on load, and can check for any potential new base packages as well with this set up.

My ad hoc tests for this are telling me that it works. Total execution time for my mini example dropped by about 150ms after the fix, with multiple replicates, so it seems like this is mostly fixed.

PS. I totally get this. This was my cop out answer to get you to create a much better solution. Thanks for the great work!
