### ISSUE TITLE
findGlobals() problem with with()

### ISSUE THREAD

**Issue by florafauna** [HenrikBengtsson/globals#48]
When using `with()`, non-global variables are reported as globals. Or do I miss something?

```
f <- function(x){
    with(x, a)
}`
codetools::findGlobals(f, merge=FALSE)$variables
[1] "a"
```

**Comment by HenrikBengtsson** [comment]
Hi, yes that's expected.  It's impossible to static code inspection to know that `a` could be part of `x`.  It's even impossible for me to know that by looking at the code.  That info can only be known at run-time when you actually have an object named `x` and known how `with()` works.  But key here is to understand that static code inspection can only do so much.

BTW, your example used the codetools package, but the globals package (this repos) gives the same:
```r
> globals::findGlobals(f)
[1] "{"    "with" "a"
```

**Comment by florafauna** [comment]
hi, thanks for the prompt reply!
I understand your argument. However, then the behaviour with `with()` and `$` are not consistent. 
```
f <- function(x){
    x$a
}
f2 <- function(x){
    with(x, a)
}
globals::findGlobals(f)
## [1] "{" "$"
globals::findGlobals(f2)
## [1] "{"    "with" "a"   
```
Shouldn't one expect the same behaviour for `with()` and `$`?

**Comment by clarkfitzg** [comment]
> Shouldn't one expect the same behaviour for with() and $?

No. `findGlobals` behaves correctly. There's a lot going on here, for example in these three cases:
```
> f <- function(x){
+     x$a
+ }
> f2 <- function(x){
+     with(x, a)
+ }

> # Case 1 - probably what most people mean when they write this code.
> x = list(a = 100)
> f(x)
[1] 100
> f2(x)
[1] 100

> # Case 2
> x = list(ab = 200)
> f(x)
[1] 200
Warning message:
partial match of 'a' to 'ab'
> f2(x)
Error in eval(substitute(expr), data, enclos = parent.frame()) :
  object 'a' not found

> # Case 3
> x = list()
> a = 300
> f(x)
NULL
> f2(x)
[1] 300
```

**Comment by florafauna** [comment]
I see. Case 3 above provides an argument for the different behaviour of `findGlobals()`. And it provides also an argument against using `with()` to access elements of a list in most situations.
