### ISSUE TITLE
BUG: The 'where' attribute may pick up the calling environment if global is NULL

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/globals#79]
From https://github.com/DavisVaughan/furrr/issues/168#issuecomment-706173455:

```r
fn <- function() {
  x <- list(null = NULL, one = 1)
  globals::as.Globals(x)
}

fn()
#> $null
#> NULL
#> 
#> $one
#> [1] 1
#> 
#> attr(,"where")
#> attr(,"where")$null
#> <environment: 0x7fa5ad858e70>
#> 
#> attr(,"where")$one
#> <environment: R_EmptyEnv>
#> 
#> attr(,"class")
#> [1] "Globals" "list"
```

This is because:

```r
environment(NULL)
```

returns the calling environment, not NULL, or `emptyenv()`.

/cc @DavisVaughan, oh my. I, either missed that very important troubleshooting of yours, or incorrectly thought it was fixed from quickly [skimming the code](https://github.com/HenrikBengtsson/globals/blob/72396160c65c7de1cfb125ffa32ce22b79456526/R/Globals-class.R#L63).  So, the "fix" in https://github.com/HenrikBengtsson/future/issues/475, ended up with the whole thing about dropping `where` and the emergency back-out `future.globals.keepWhere` solution, which in turn gives rise to https://github.com/HenrikBengtsson/future/issues/608. Crossing my finger that fixing this bug here will allow me to withdraw dropping `where`. It's clear that I have way too much on my plate at times and missing the important details served to me.

**Comment by DavisVaughan** [comment]
> will allow me to withdraw dropping where. 

That would be great!

> I have way too much on my plate at times

Never feel like you ever have to rush to answer any of my bug reports. I have all the time in the world to wait, and would much rather have you working at your best! It sounds to me like you need to take a break and go paragliding again 😆

**Comment by HenrikBengtsson** [comment]
Thanks. Trust me, if the all these storms that been coming in this year would stop for a while, I'd been in the sky right now ... and there's no future up there - only now
