### ISSUE TITLE
`cleanup` fails on environments with strict extraction

### ISSUE THREAD

**Issue by klmr** [HenrikBengtsson/globals#80]
**Describe the bug**

The original issue was described in klmr/box#285. In a nutshell, when a subclass of `environment` overrides `$` to raise an error on non-existent names, `cleanup` stops with an error because `cleanup.Globals` calls `isPackageNamespace(env)` which, in turn, attempts to read (the non-existent) `env$.packageName`.

This problem occurs in conjunction with ‘box’ because [‘box’ module environments](https://klmr.me/box/articles/mod-env-hierarchy.html#module-export-environment-1) are environments with a [strict implementation of `$`](https://github.com/klmr/box/blob/024dbf89ebb13c7b35988c0d18ec6e0378121dba/src/lookup.c#L24-L49) to prevent bugs (similar to how `pkg::does_not_exist` will raise an error). But the issue is not specific to ‘box’ as the following reprex shows.

**Reproduce example**

```r
e = structure(new.env(), class = 'xenv')

`$.xenv` = function (e, name) {
    if (! exists(name, envir = e)) stop('not found')
    get(name, envir = e)
}

e$foo = 1

g = globals::globalsByName('foo', envir = e)
globals::cleanup(g)
```

Raises the error message:

> ```
> Error in `$.xenv`(env, ".packageName") : not found
> ```

**Expected behavior**

`globals::cleanup` should succeed.

**Session information**

Please share your session information *after* the error has occurred so that we also see which packages and versions are involved;

```r
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.1   codetools_0.2-18 globals_0.15.0
```

**Comment by HenrikBengtsson** [comment]
Thanks for the detailed report and reproducible example. It was definitely a mistake `$` on a "classed" environment could fail.

I've fixed this in the develop branch (commit e00ecc7e7).

**Comment by dereckdemezquita** [comment]
@HenrikBengtsson thank you I tested it with my code and it works. I just have to explicitly call in my globals using the argument `future.globals` as a character vector in the `future_lapply` function!

Thank you :)

**Comment by HenrikBengtsson** [comment]
**globals** 0.15.1, fixing this, is now on CRAN
