### ISSUE TITLE
Support for `utils::globalVariables()`

### ISSUE THREAD

**Issue by MichalLauer** [HenrikBengtsson/globals#89]
If a function uses [data masking](https://dplyr.tidyverse.org/articles/programming.html), the function `globals::globalsOf(...)` throws an error, as expected.

``` r
example <- function() {
  mtcars |>
    dplyr::filter(cyl == 4)
}

globals::globalsOf(example, mustExist = T)
#> Error in globalsByName(names, envir = envir, mustExist = mustExist): Identified global objects via static code inspection (function (); {; dplyr::filter(mtcars, cyl == 4); }). Failed to locate global object in the relevant environments: 'cyl'
```

This can be fixed with two things: defining the variable as NULL
``` r
example <- function() {
  cyl <- NULL
  mtcars |>
    dplyr::filter(cyl == 4)
}

globals::globalsOf(example, mustExist = T)
# No error thrown...
```

or using [pronouns](https://rlang.r-lib.org/reference/dot-data.html).

``` r
example <- function() {
  mtcars |>
    dplyr::filter(rlang::.data$cyl == 4)
}

globals::globalsOf(example, mustExist = T)
# No error thrown...
```

However, when a global variable is defined using the `utils::globalVariables` function, the `globals::globalsOf` function throws an error.

``` r
example <- function() {
  utils::globalVariables(c("cyl"))

  mtcars |>
    dplyr::filter(cyl == 4)
}

globals::globalsOf(example, mustExist = T)
#> Error in globalsByName(names, envir = envir, mustExist = mustExist): Identified global objects via static code inspection (function (); {; utils::globalVariables(c("cyl")); dplyr::filter(mtcars, cyl == 4); }). Failed to locate global object in the relevant environments: 'cyl'
```

This is especially painful when developing R Shiny applications as a package.

I think adding this functionality would be a great addition, because is recommended in the book [R Packages (2e)](https://r-pkgs.org/package-within.html#echo-a-working-package) and in my humble opinion, it makes sense as the variable is defined globally.

What do you guys think? :)

**Comment by schloerke** [comment]
> because is recommended in the book [R Packages (2e)](https://r-pkgs.org/package-within.html#echo-a-working-package)

From R Packages (2e)...
> The “no visible binding” note is a peculiarity of using dplyr and unquoted variable names inside a package, where the use of bare variable names (english and temp) looks suspicious. You can add either of these lines to any file below R/ to eliminate this note

Using `utils::globalVariables()` is there to "eliminate this note". It does not _actually_ set a global value that can be found.

-----------------------

Previous issue on finding globals given non-standard evaluation: https://github.com/HenrikBengtsson/globals/issues/35

-----------------------

I don't believe `utils::globalVariables()` should be supported by `{globals}` even though the name implies "setting a globally available name".

**Comment by MichalLauer** [comment]
Hello @schloerke, understood. Thanks for the quick answer :)
